### ISSUE TITLE
azure-iot-bridge: 403: Forbidden

### ISSUE THREAD

**Issue by zx1234r** [tim-hellhake/azure-iot-bridge#3] opened 2019-11-19 08:29 UTC
Hello and thank you so much for a very good job on the addon. When i try to configure it however, i run into this error. I followed your instructions to the letter but it seems i am missing something. I double and triple checked that the token is correct and that the connection string is exactly copied to the letter from the SharedAccessPolicies, iothubowner, primary connection string.
I then tried creating a device in the azure iot hub, copied it's own primary connection string and typed this to the addon's configuration, in which case i got a 
"azure-iot-bridge: { ArgumentError: The connection string is missing the property: SharedAccessKeyName name: 'ArgumentError' }" error. 
Is there something that i am missing?

**Comment by tim-hellhake** [comment] 2019-11-19 12:11
> Hello and thank you so much for a very good job on the addon

Thank you very much.
I'm always grateful for any feedback.

> The connection string is missing the property: SharedAccessKeyName

The device connection string has different properties than the hub connection string.
This happens if you try to connect to a hub with a device connection string.

In the title, you mentioned `403: Forbidden`.
This looks like the addon fails to connect to the gateway.
Either the token is incorrect or does not have enough rights.
Could you provide more logs?
I will add more debug logs as a next so we look into this further.

**Comment by zx1234r** [comment] 2019-11-19 12:28
Thank you very much for your fast response. It is always good to hear back from developers.
I am using the json token, i assumed that this was the one required. I also made sure that during creation, i gave read write access. i have done the process a few times over and over again, each time trying the newly generated token but every time i experience the same error.

some more logs:

2019-11-19 08:20:02.100 INFO   : Loading add-on: azure-iot-bridge
2019-11-19 08:20:02.968 INFO   : azure-iot-bridge: Opening database: /home/pi/.mozilla-iot/config/db.sqlite3
2019-11-19 08:20:03.678 INFO   : azure-iot-bridge: Loading add-on azure-iot-bridge from /home/pi/.mozilla-iot/addons/azure-iot-bridge
2019-11-19 08:20:04.345 INFO   : azure-iot-bridge: Unhandled Rejection
2019-11-19 08:20:04.347 ERROR  : azure-iot-bridge: 403: Forbidden

**Comment by tim-hellhake** [comment] 2019-11-19 12:45
Just to be sure: Did you create your token via `http://localhost:8080/oauth/authorize?response_type=code&client_id=local-token&scope=/things:readwrite`?

The token in the first box is the correct one.
There should also be a curl command.
Can you try if it works?

**Comment by zx1234r** [comment] 2019-11-19 17:37
Unfortunately i don't have the ability to test curl commands right now. I revoked the token and i reissued a new one using your provided url. Unfortunately i keep getting the 403: forbidden error.
I will try to test the curl as soon as possible.

**Comment by zx1234r** [comment] 2019-11-24 14:08
I have tried everything that comes to mind and even though i can successfully connect with curl, nothing ever works for the azure iot connection. The produced error indeed shows that something in the authentication process is wrong but i really cannot dig any further without some verbosity.
The token is correct, the connection string is correct.....

However, in the overview tab of my azure portal, there is reference to 1 device and that this device has already sent 4 messages.  But no devices are listed in the "IoT Devices" Tab. The whole process seems pretty straightforward but i think i am missing something.

![image](https://user-images.githubusercontent.com/57939055/69495807-bf624c00-0ed3-11ea-90a4-1d208ccd70d8.png)

**Comment by tim-hellhake** [comment] 2019-11-24 21:10
> The curl seems to be working.

Thank you for testing it.

> The token is correct, the connection string is correct.....

I think I figured out what is happening.
I should have paid more attention to the HTTP response code.
If there would be a problem with the token, the correct error code would 401 (_Unauthorized_).
Instead, the gateway returns 403 (_Forbidden_), which means that it won't accept the request at all.
The gateway starts a redirector on the HTTP port as soon as the HTTPS port is active.
However, the redirector answers with a 403 if you send it an authorization token.
I updated my client library, so it switches to https if the redirector is active.

**Comment by tim-hellhake** [comment] 2019-11-24 21:44
The PR for `0.1.5` is open.
As soon as it's merged you can test it.

**Comment by zx1234r** [comment] 2019-11-26 13:34
Thank you so much for everything so far. I hate to be the bringer of bad news, but unfortunately the same error keeps coming back. I updated the add-on to version 0.1.5 as shown in the screenshot. I can remotely connect to my device with curl as shown in the second screenshot so the token is definitely correct. I successfully connected from a remote network as well but unfortunately i get the error 403: Forbidden

```
2019-11-26 14:22:06.287 INFO   : azure-iot-bridge: Opening database: /home/pi/.mozilla-iot/config/db.sqlite3
2019-11-26 14:22:06.958 INFO   : azure-iot-bridge: Loading add-on azure-iot-bridge from /home/pi/.mozilla-iot/addons/azure-iot-bridge
2019-11-26 14:22:07.617 INFO   : azure-iot-bridge: Unhandled Rejection
2019-11-26 14:22:07.619 ERROR  : azure-iot-bridge: 403: Forbidden
```

![image](https://user-images.githubusercontent.com/57939055/69637577-9079e080-1061-11ea-8f7a-015b19ee9d53.png)
![image](https://user-images.githubusercontent.com/57939055/69637737-ed759680-1061-11ea-81fa-f59f308e6eb0.png)

**Comment by tim-hellhake** [comment] 2019-11-26 13:56
> but unfortunately the same error keeps coming back

I'll try to reproduce with a fresh gateway.
Maybe this brings us closer to the error source.

Could you attach more of the logs?
I'm searching for something like `Probing port` and `HTTPS seems to be active, using port`.

**Comment by zx1234r** [comment] 2019-11-26 14:52
The logs that i can access from inside the gateway `Developer --> View internal logs`, only show those lines:

```
2019-11-26 14:21:12.962 INFO   : Fetching add-on https://s3-us-west-2.amazonaws.com/mozilla-gateway-addons/azure-iot-bridge-0.1.5.tgz as /tmp/QMMkty/azure-iot-bridge.tar.gz
2019-11-26 14:21:28.858 INFO   : Expanding add-on /tmp/QMMkty/azure-iot-bridge.tar.gz
2019-11-26 14:21:40.719 INFO   : Loading add-on: azure-iot-bridge
2019-11-26 14:21:41.643 INFO   : azure-iot-bridge: Opening database: /home/pi/.mozilla-iot/config/db.sqlite3
2019-11-26 14:21:42.327 INFO   : azure-iot-bridge: Loading add-on azure-iot-bridge from /home/pi/.mozilla-iot/addons/azure-iot-bridge
2019-11-26 14:21:42.980 INFO   : azure-iot-bridge: Unhandled Rejection
2019-11-26 14:21:42.981 ERROR  : azure-iot-bridge: 403: Forbidden
2019-11-26 14:22:01.069 INFO   : Unloading AzureIotBridge
2019-11-26 14:22:01.072 INFO   : azure-iot-bridge: Adapter: AzureIotBridge unloaded
2019-11-26 14:22:05.390 INFO   : Loading add-on: azure-iot-bridge
2019-11-26 14:22:06.287 INFO   : azure-iot-bridge: Opening database: /home/pi/.mozilla-iot/config/db.sqlite3
2019-11-26 14:22:06.958 INFO   : azure-iot-bridge: Loading add-on azure-iot-bridge from /home/pi/.mozilla-iot/addons/azure-iot-bridge
2019-11-26 14:22:07.617 INFO   : azure-iot-bridge: Unhandled Rejection
2019-11-26 14:22:07.619 ERROR  : azure-iot-bridge: 403: Forbidden
```
I will try if i can see anything more through ssh once i get home.

**Comment by tim-hellhake** [comment] 2019-11-26 18:31
Thanks for the logs.
They pointed me in the right direction.
A new update is in the pipeline.

**Comment by zx1234r** [comment] 2019-11-27 10:39
Awesome! It works flawlessly. I don't however see all my devices, only 4 but i will dig around to see what this problem is. Thanx a lot for your effort! Great work!

**Comment by tim-hellhake** [comment] 2019-11-27 23:43
> Awesome! It works flawlessly

Finally!
Thank you for your patience.

> I don't however see all my devices

There should be a lot of logs that tell you what is happening in the background.
I'm closing this issue now because the original problem is solved.
Can you please open a new issue if the problem persists?

> Thanx a lot for your effort! Great work!

I'm always happy to help :)

**Closed by tim-hellhake** 2019-11-27 23:43 UTC
